// components/SectionGallery.tsx
"use client";

import Image from "next/image";

const BASE_PATH = "/SDP_team_52_demo_test";

export default function SectionGallery() {
  const images = ["demo1.png", "demo2.png"];

  return (
    <section id="gallery" className="anchor">
      <div className="container section">
        <h2>Gallery</h2>
        <p style={{ marginTop: 8, opacity: 0.85 }}>
          A showcase of demo results generated by our reconstruction pipeline.
        </p>

        <div
          style={{
            display: "grid",
            gap: 24,
            marginTop: 20,
            gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
          }}
        >
          {images.map((name, idx) => (
            <div
              key={idx}
              style={{
                position: "relative",
                width: "100%",
                paddingBottom: "100%", 
                borderRadius: 16,
                overflow: "hidden",
                background: "rgba(255,255,255,0.05)",
              }}
            >
              <Image
                src={`${BASE_PATH}/${name}`}
                alt={`gallery-${idx}`}
                fill
                style={{
                  objectFit: "contain", 
                  padding: 20,
                }}
              />
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
