// components/SectionGallery.tsx

"use client";

export default function SectionGallery() {
  return (
    <section id="gallery" className="anchor">
      <div className="container section">
        <h2>Gallery</h2>
        <p style={{ marginTop: 8, opacity: 0.85 }}>
          A showcase of demo results generated by our reconstruction pipeline.
        </p>

        <div
          style={{
            display: "grid",
            gap: 18,
            marginTop: 20,
            gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
          }}
        >
          {[
            "/demo1.png",
            "/demo2.png",
          ].map((src, idx) => (
            <div
              key={idx}
              className="card"
              style={{
                padding: 0,
                overflow: "hidden",
                borderRadius: 16,
                background: "rgba(255,255,255,0.04)",
              }}
            >
              <img
                src={src}
                alt={`gallery-${idx}`}
                style={{
                  width: "100%",
                  height: 180,
                  objectFit: "cover",
                  transition: "all 0.25s ease",
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.transform = "scale(1.05)";
                  e.currentTarget.style.opacity = "0.9";
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.transform = "scale(1)";
                  e.currentTarget.style.opacity = "1";
                }}
              />
            </div>
          ))}
        </div>

      </div>
    </section>
  );
}
